// Sample data structure for the Fail Code Management System

// Warranty Types
const warrantyTypes = [
    { id: 'WTY001', name: '"Postponed" Standard Shell Warranty' },
    { id: 'WTY002', name: '"Temporary" 18 months conversion WTY' },
    { id: 'WTY003', name: '12 months standard warranty' },
    { id: 'WTY004', name: '24 Month standard warranty' },
    { id: 'WTY005', name: '27 Month standard warranty (entertainer)' },
    { id: 'WTY006', name: '28 month standard warranty (Entertainer)' },
    { id: 'WTY007', name: '36 Month Extended Warranty' },
    { id: 'WTY008', name: '48 Month Premium Warranty' },
    { id: 'WTY009', name: '60 Month Commercial Warranty' },
    { id: 'WTY010', name: 'Agriculture Equipment Warranty' },
    { id: 'WTY011', name: 'Construction Equipment Warranty' },
    { id: 'WTY012', name: 'Mining Equipment Warranty' },
    { id: 'WTY013', name: 'Forestry Equipment Warranty' },
    { id: 'WTY014', name: 'Marine Equipment Warranty' },
    { id: 'WTY015', name: 'Industrial Equipment Warranty' },
    { id: 'WTY016', name: 'Transportation Fleet Warranty' },
    { id: 'WTY017', name: 'Emergency Vehicle Warranty' },
    { id: 'WTY018', name: 'School Bus Warranty' },
    { id: 'WTY019', name: 'Transit Bus Warranty' },
    { id: 'WTY020', name: 'Coach Bus Warranty' },
    { id: 'WTY021', name: 'Shuttle Bus Warranty' },
    { id: 'WTY022', name: 'Tour Bus Warranty' },
    { id: 'WTY023', name: 'Charter Bus Warranty' },
    { id: 'WTY024', name: 'City Bus Warranty' },
    { id: 'WTY025', name: 'Intercity Bus Warranty' },
    { id: 'WTY026', name: 'Airport Shuttle Warranty' },
    { id: 'WTY027', name: 'Hotel Shuttle Warranty' },
    { id: 'WTY028', name: 'Medical Transport Warranty' },
    { id: 'WTY029', name: 'Ambulance Warranty' },
    { id: 'WTY030', name: 'Fire Truck Warranty' },
    { id: 'WTY031', name: 'Police Vehicle Warranty' },
    { id: 'WTY032', name: 'Utility Vehicle Warranty' },
    { id: 'WTY033', name: 'Maintenance Vehicle Warranty' },
    { id: 'WTY034', name: 'Delivery Vehicle Warranty' },
    { id: 'WTY035', name: 'Cargo Vehicle Warranty' },
    { id: 'WTY036', name: 'Refrigerated Vehicle Warranty' },
    { id: 'WTY037', name: 'Fuel Truck Warranty' },
    { id: 'WTY038', name: 'Water Truck Warranty' },
    { id: 'WTY039', name: 'Garbage Truck Warranty' },
    { id: 'WTY040', name: 'Street Sweeper Warranty' },
    { id: 'WTY041', name: 'Snow Plow Warranty' },
    { id: 'WTY042', name: 'Salt Truck Warranty' },
    { id: 'WTY043', name: 'Tow Truck Warranty' },
    { id: 'WTY044', name: 'Recovery Vehicle Warranty' },
    { id: 'WTY045', name: 'Mobile Crane Warranty' },
    { id: 'WTY046', name: 'Boom Truck Warranty' },
    { id: 'WTY047', name: 'Concrete Mixer Warranty' },
    { id: 'WTY048', name: 'Dump Truck Warranty' },
    { id: 'WTY049', name: 'Flatbed Truck Warranty' },
    { id: 'WTY050', name: 'Box Truck Warranty' },
    { id: 'WTY051', name: 'Panel Van Warranty' },
    { id: 'WTY052', name: 'Passenger Van Warranty' },
    { id: 'WTY053', name: 'Cargo Van Warranty' },
    { id: 'WTY054', name: 'Minibus Warranty' },
    { id: 'WTY055', name: 'Microbus Warranty' }
];

// Fail Codes mapped to Warranty Types
const failCodes = {
    'WTY001': [
        { code: 'WB5001', name: 'Postponed warranty activation pending' },
        { code: 'WB5002', name: 'Shell warranty documentation review' },
        { code: 'WB5003', name: 'Standard shell inspection required' },
        { code: 'WB5004', name: 'Postponed maintenance schedule adjustment' },
        { code: 'WB5005', name: 'Shell warranty coverage verification' },
        { code: 'WB5006', name: 'Postponed service authorization' },
        { code: 'WB5007', name: 'Standard shell component evaluation' },
        { code: 'WB5008', name: 'Warranty postponement documentation' },
        { code: 'WB5009', name: 'Shell warranty terms clarification' },
        { code: 'WB5010', name: 'Postponed warranty claim processing' }
    ],
    'WTY002': [
        { code: '07.00-2', name: 'ZF Transmission' },
        { code: '23.05', name: 'Windshield Wipers, Washers' },
        { code: '06.18', name: 'Windshield Wiper Motor' },
        { code: '18.06', name: 'Windshield (stress crack)' },
        { code: '13.00', name: 'Wheels (General)' },
        { code: '13.01', name: 'Wheels' },
        { code: '25.00', name: 'Wheelchair lift (General)' },
        { code: '23.14', name: 'Wheel Odometer' },
        { code: '13.01-1', name: 'Wheel Balancing' },
        { code: '18.10', name: 'Watertightness' }
    ],
    'WTY003': [
        { code: '07.00-2', name: 'ZF Transmission' },
        { code: '23.05', name: 'Windshield Wipers, Washers' },
        { code: '06.18', name: 'Windshield Wiper Motor' },
        { code: '18.06', name: 'Windshield (stress crack)' },
        { code: '13.00', name: 'Wheels (General)' }
    ],
    'WTY004': [
        { code: '13.01', name: 'Wheels' },
        { code: '25.00', name: 'Wheelchair lift (General)' },
        { code: '23.14', name: 'Wheel Odometer' },
        { code: '13.01-1', name: 'Wheel Balancing' },
        { code: '18.10', name: 'Watertightness' },
        { code: '24.05', name: 'Warning Systems' },
        { code: '07.01', name: 'Transmission Oil Cooler' },
        { code: '07.02', name: 'Transmission Fluid' },
        { code: '07.03', name: 'Transmission Control Module' },
        { code: '23.06', name: 'Windshield Washer Pump' },
        { code: '06.19', name: 'Windshield Wiper Linkage' },
        { code: '18.07', name: 'Window Seals' },
        { code: '13.02', name: 'Wheel Bearings' },
        { code: '25.01', name: 'Wheelchair Lift Motor' },
        { code: '23.15', name: 'Wheel Speed Sensor' },
        { code: '18.11', name: 'Water Damage' },
        { code: '24.06', name: 'Warning Light Malfunction' },
        { code: '07.04', name: 'Transmission Mount' },
        { code: '23.07', name: 'Windshield Washer Reservoir' },
        { code: '06.20', name: 'Windshield Wiper Blade' }
    ],
    'WTY005': [
        { code: 'FC008', name: '27 Month standard warranty (entertainer)' }
    ],
    'WTY006': [
        { code: 'FC012', name: '28 month standard warranty (Entertainer)' }
    ]
};

// Fail Descriptions mapped to Fail Codes
const failDescriptions = {
    'FC001': 'Critical hardware component has failed and requires immediate replacement. System is non-operational.',
    'FC002': 'Software application is experiencing malfunction causing system instability and data corruption.',
    'FC003': 'Power supply unit is not providing adequate power causing intermittent shutdowns and performance issues.',
    'FC004': 'Display unit shows distorted images, flickering, or complete blackout affecting user productivity.',
    'FC005': 'Network connectivity is lost or unstable preventing access to network resources and internet.',
    'FC006': 'Component performance has degraded over time affecting overall system efficiency and reliability.',
    'FC007': 'System performance has significantly decreased below acceptable thresholds impacting user experience.',
    'FC008': 'Hardware or software components are not compatible causing conflicts and system instability.',
    'FC009': 'Firmware has become corrupted requiring reinstallation or replacement of affected components.',
    'FC010': 'System is overheating due to inadequate cooling or thermal management causing potential damage.',
    'FC011': 'Critical system failure has occurred requiring immediate attention and emergency response procedures.',
    'FC012': 'Data has been lost due to system failure, corruption, or accidental deletion requiring recovery procedures.',
    'FC013': 'Security breach has been detected compromising system integrity and requiring immediate containment.',
    'FC014': 'System performance has degraded significantly affecting business operations and user productivity.',
    'FC015': 'Service interruption has occurred affecting business continuity and customer satisfaction.',
    'FC016': 'Manufacturing defect has been identified in the product requiring recall or replacement procedures.',
    'FC017': 'Design flaw has been discovered affecting product functionality and requiring engineering review.',
    'FC018': 'Material failure has occurred due to substandard materials or manufacturing processes.',
    'FC019': 'Assembly error during manufacturing has resulted in product malfunction or safety concerns.',
    'FC020': 'Quality control process has failed to identify defects before product shipment.',
    'FC021': 'Third party component has failed affecting overall system functionality and reliability.',
    'FC022': 'Integration issues between different systems or components causing operational problems.',
    'FC023': 'Vendor support is inadequate or unavailable affecting problem resolution and maintenance.',
    'FC024': 'Software license violation has been detected requiring immediate compliance action.',
    'FC025': 'Regulatory compliance issue has been identified requiring corrective action and reporting.',
    'FC026': 'Service level agreement has been breached affecting customer satisfaction and contract terms.',
    'FC027': 'Response time requirements have been violated affecting service quality and customer expectations.',
    'FC028': 'Scheduled maintenance has been overdue increasing risk of system failure and downtime.',
    'FC029': 'Contract terms have been violated requiring legal review and corrective action.',
    'FC030': 'Required resources are unavailable affecting service delivery and operational capability.',
    'FC031': 'Preventive maintenance procedures have failed to prevent system failure or degradation.',
    'FC032': 'Scheduled maintenance activities have encountered issues affecting system availability.',
    'FC033': 'Emergency maintenance is required due to critical system failure or safety concerns.',
    'FC034': 'Maintenance window has been exceeded affecting system availability and service levels.',
    'FC035': 'Equipment downtime has exceeded acceptable limits affecting business operations.',
    'FC036': 'Replacement part has manufacturing defect affecting system functionality and reliability.',
    'FC037': 'Part has worn beyond acceptable limits requiring replacement to maintain system performance.',
    'FC038': 'Replacement part is not compatible with existing system configuration.',
    'FC039': 'Required replacement part is not available affecting repair timeline and system downtime.',
    'FC040': 'Part installation error has occurred affecting system functionality and potentially causing damage.',
    'FC041': 'Labor quality does not meet required standards affecting work output and system reliability.',
    'FC042': 'Skill gap has been identified in technical personnel affecting service quality and efficiency.',
    'FC043': 'Additional training is required for personnel to meet job requirements and standards.',
    'FC044': 'Certification requirements have not been met affecting compliance and service authorization.',
    'FC045': 'Work standards have been violated affecting quality and potentially causing safety issues.',
    'FC046': 'Multiple systems have failed simultaneously requiring comprehensive recovery procedures.',
    'FC047': 'Multiple components have failed affecting overall system functionality and reliability.',
    'FC048': 'Cascading failure has occurred where one failure has triggered additional system failures.',
    'FC049': 'Environmental factors have caused damage to equipment requiring assessment and repair.',
    'FC050': 'Force majeure event has occurred affecting operations and requiring emergency response.',
    'FC051': 'Claim exceeds limited warranty coverage requiring additional authorization or payment.',
    'FC052': 'Warranty exclusion applies to the reported issue affecting coverage and repair authorization.',
    'FC053': 'Only partial warranty coverage applies requiring customer contribution for full repair.',
    'FC054': 'Warranty deductible applies requiring customer payment before repair authorization.',
    'FC055': 'Warranty coverage has limitations affecting the scope of repair or replacement.',
    'FC056': 'Cross-border warranty issue affecting service delivery and coverage terms.',
    'FC057': 'Currency exchange fluctuations affecting warranty cost calculations and billing.',
    'FC058': 'International regulatory compliance requirements affecting warranty service delivery.',
    'FC059': 'Import or export restrictions affecting parts availability and service delivery.',
    'FC060': 'Conflicting international laws affecting warranty terms and service obligations.',
    'FC061': 'Business operations have been interrupted affecting productivity and revenue generation.',
    'FC062': 'Revenue loss has occurred due to system failure affecting business financial performance.',
    'FC063': 'Productivity has been significantly impacted affecting business operations and efficiency.',
    'FC064': 'Customer satisfaction has been negatively affected requiring immediate attention and resolution.',
    'FC065': 'Market share loss has occurred due to system reliability issues affecting competitive position.',
    'FC066': 'Consumer rights have been violated requiring immediate corrective action and compensation.',
    'FC067': 'Product safety issue has been identified requiring immediate action to prevent harm.',
    'FC068': 'User experience has been negatively affected requiring interface or functionality improvements.',
    'FC069': 'Accessibility requirements have not been met affecting user access and compliance.',
    'FC070': 'Consumer protection regulations have been breached requiring compliance action.',
    'FC071': 'Professional standards have been breached affecting service quality and reputation.',
    'FC072': 'Industry compliance requirements have not been met requiring corrective action.',
    'FC073': 'Professional liability issue has been identified requiring legal review and action.',
    'FC074': 'Professional certification requirements have not been met affecting service authorization.',
    'FC075': 'Professional ethics have been violated requiring disciplinary action and corrective measures.'
};

// Sample fail code records for the table
let failCodeRecords = [
    {
        id: 1,
        warrantyType: 'WTY001',
        warrantyTypeName: '"Postponed" Standard Shell Warranty',
        failCode: 'WB5001',
        failCodeName: 'Postponed warranty activation pending',
        isActive: true,
        createdDate: '2024-01-15',
        lastModified: '2024-01-15'
    },
    {
        id: 2,
        warrantyType: 'WTY001',
        warrantyTypeName: '"Postponed" Standard Shell Warranty',
        failCode: 'WB5002',
        failCodeName: 'Shell warranty documentation review',
        isActive: true,
        createdDate: '2024-01-16',
        lastModified: '2024-01-16'
    },
    {
        id: 3,
        warrantyType: 'WTY001',
        warrantyTypeName: '"Postponed" Standard Shell Warranty',
        failCode: 'WB5003',
        failCodeName: 'Standard shell inspection required',
        isActive: false,
        createdDate: '2024-01-17',
        lastModified: '2024-01-17'
    },
    {
        id: 4,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '07.00-2',
        failCodeName: 'ZF Transmission',
        isActive: false,
        createdDate: '2024-01-18',
        lastModified: '2024-01-18'
    },
    {
        id: 14,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '23.05',
        failCodeName: 'Windshield Wipers, Washers',
        isActive: true,
        createdDate: '2024-01-28',
        lastModified: '2024-01-28'
    },
    {
        id: 15,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '06.18',
        failCodeName: 'Windshield Wiper Motor',
        isActive: true,
        createdDate: '2024-01-29',
        lastModified: '2024-01-29'
    },
    {
        id: 16,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '18.06',
        failCodeName: 'Windshield (stress crack)',
        isActive: true,
        createdDate: '2024-01-30',
        lastModified: '2024-01-30'
    },
    {
        id: 17,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '13.00',
        failCodeName: 'Wheels (General)',
        isActive: true,
        createdDate: '2024-01-31',
        lastModified: '2024-01-31'
    },
    {
        id: 18,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '13.01',
        failCodeName: 'Wheels',
        isActive: true,
        createdDate: '2024-02-01',
        lastModified: '2024-02-01'
    },
    {
        id: 19,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '25.00',
        failCodeName: 'Wheelchair lift (General)',
        isActive: true,
        createdDate: '2024-02-02',
        lastModified: '2024-02-02'
    },
    {
        id: 20,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '23.14',
        failCodeName: 'Wheel Odometer',
        isActive: true,
        createdDate: '2024-02-03',
        lastModified: '2024-02-03'
    },
    {
        id: 21,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '13.01-1',
        failCodeName: 'Wheel Balancing',
        isActive: true,
        createdDate: '2024-02-04',
        lastModified: '2024-02-04'
    },
    {
        id: 22,
        warrantyType: 'WTY002',
        warrantyTypeName: '"Temporary" 18 months conversion WTY',
        failCode: '18.10',
        failCodeName: 'Watertightness',
        isActive: true,
        createdDate: '2024-02-05',
        lastModified: '2024-02-05'
    },
    {
        id: 5,
        warrantyType: 'WTY003',
        warrantyTypeName: '12 months standard warranty',
        failCode: '23.05',
        failCodeName: 'Windshield Wipers, Washers',
        isActive: true,
        createdDate: '2024-01-19',
        lastModified: '2024-01-19'
    },
    {
        id: 6,
        warrantyType: 'WTY003',
        warrantyTypeName: '12 months standard warranty',
        failCode: '06.18',
        failCodeName: 'Windshield Wiper Motor',
        isActive: true,
        createdDate: '2024-01-20',
        lastModified: '2024-01-20'
    },
    {
        id: 7,
        warrantyType: 'WTY003',
        warrantyTypeName: '12 months standard warranty',
        failCode: '18.06',
        failCodeName: 'Windshield (stress crack)',
        isActive: true,
        createdDate: '2024-01-21',
        lastModified: '2024-01-21'
    },
    {
        id: 8,
        warrantyType: 'WTY003',
        warrantyTypeName: '12 months standard warranty',
        failCode: '13.00',
        failCodeName: 'Wheels (General)',
        isActive: true,
        createdDate: '2024-01-22',
        lastModified: '2024-01-22'
    },
    {
        id: 9,
        warrantyType: 'WTY004',
        warrantyTypeName: '24 Month standard warranty',
        failCode: 'WB3175',
        failCodeName: 'ACS Number Software Re-programming',
        isActive: true,
        createdDate: '2024-01-23',
        lastModified: '2024-01-23'
    },
    {
        id: 10,
        warrantyType: 'WTY004',
        warrantyTypeName: '24 Month standard warranty',
        failCode: 'WB3406',
        failCodeName: 'add insulation on pipes',
        isActive: true,
        createdDate: '2024-01-24',
        lastModified: '2024-01-24'
    },
    {
        id: 11,
        warrantyType: 'WTY004',
        warrantyTypeName: '24 Month standard warranty',
        failCode: 'WB8127',
        failCodeName: 'Adding DB9 Connector in +RF0 Panel',
        isActive: true,
        createdDate: '2024-01-25',
        lastModified: '2024-01-25'
    },
    {
        id: 9,
        warrantyType: 'WTY004',
        warrantyTypeName: '24 Month standard warranty',
        failCode: '13.01-1',
        failCodeName: 'Wheel Balancing',
        isActive: true,
        createdDate: '2024-01-23',
        lastModified: '2024-01-23'
    },
    {
        id: 10,
        warrantyType: 'WTY004',
        warrantyTypeName: '24 Month standard warranty',
        failCode: '18.10',
        failCodeName: 'Watertightness',
        isActive: true,
        createdDate: '2024-01-24',
        lastModified: '2024-01-24'
    }
];

// Export data for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        warrantyTypes,
        failCodes,
        failDescriptions,
        failCodeRecords
    };
}
